### ISSUE TITLE
Fixed apy

### ISSUE THREAD

**Issue by Evert0x** [sherlock-protocol/sherlock-v2-indexer#11]
TODO
- [ ] include counter in `StakingPositions` of how many times the position has been restaked
- [ ] create apy field like `pos["usdc_apy"]`. 

We don't read the `pos["usdc_apy"]` value from the database but `if pos.restaked == 0 && pos.id <= settings.LAST_POSITION_ID_FOR_15PERC_APY` we'll make it `0.15` otherwise we use `indexer_data.apy`

**Comment by rcstanciu** [comment]
> TODO
> 
> * [ ]  include counter in `StakingPositions` of how many times the position has been restaked

Easy, based on `event Restaked(uint256 indexed tokenID);`

> * [ ]  create apy field like `pos["usdc_apy"]`.
> 
> We don't read the `pos["usdc_apy"]` value from the database but `if pos.restaked == 0 && pos.id <= settings.LAST_POSITION_ID_FOR_15PERC_APY` we'll make it `0.15` otherwise we use `indexer_data.apy`

Easy as well.
